/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gaming_setup.glb -T 
Files: gaming_setup.glb [26.77MB] > D:\Projects\portfolio-3d\public\models\gaming_setup-transformed.glb [1.53MB] (94%)
Author: Hamza_Tariq (https://sketchfab.com/Hamza_Tariq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-setup-6ba24900db4e4031a1d263cd324fead8
Title: Gaming setup
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function ComputerSetup(props) {
  const { nodes, materials } = useGLTF('models/gaming_setup-transformed.glb')
  const texture = useTexture('/myScreen.png')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MouseThermaltakeBlack015_Material001_0.geometry} material={materials.PaletteMaterial001} position={[1.102, 0.282, -0.474]} rotation={[0, Math.PI / 2, 0]} scale={0.285} />
      <mesh geometry={nodes.MouseThermaltakeBlack015_Material004_0.geometry} material={materials['Material.004']} position={[1.102, 0.282, -0.474]} rotation={[0, Math.PI / 2, 0]} scale={0.285} />
      <mesh geometry={nodes.main_controler_E_red001_0.geometry} material={materials.PaletteMaterial002} position={[-1.188, 0.424, -1.56]} rotation={[-1.564, 0.019, 1.214]} scale={8.728} />
      <mesh geometry={nodes.main_controler_Black001_0.geometry} material={materials.PaletteMaterial001} position={[-1.188, 0.424, -1.56]} rotation={[-1.564, 0.019, 1.214]} scale={8.728} />
      <mesh geometry={nodes.Cube011_screen001_0.geometry} material={materials['screen.001']} position={[0.903, 1.2, 5.781]} rotation={[-Math.PI / 2, 0.746, 1.564]} scale={8.45} />
      <mesh geometry={nodes.Cube_Material_0_Material005_0.geometry} material={materials['Material.005']} position={[-0.61, 0.096, 1.561]} rotation={[0, 0, Math.PI]} scale={[-3.102, 0.088, 6.15]} />
      <mesh geometry={nodes.Object_520_Tasten_0_Material074_39001_0.geometry} material={materials['Material.074_39.001']} position={[0.955, 0.24, 2.19]} rotation={[Math.PI / 2, -0.09, -Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_520_Tasten_0_Material074_32001_0.geometry} material={materials['Material.074_32.001']} position={[0.955, 0.24, 2.19]} rotation={[Math.PI / 2, -0.09, -Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_520_Tasten_0_Material074_33001_0.geometry} material={materials['Material.074_33.001']} position={[0.955, 0.24, 2.19]} rotation={[Math.PI / 2, -0.09, -Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_520_Tasten_0_Material074_34001_0.geometry} material={materials['Material.074_34.001']} position={[0.955, 0.24, 2.19]} rotation={[Math.PI / 2, -0.09, -Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_520_Tasten_0_Material074_35001_0.geometry} material={materials['Material.074_35.001']} position={[0.955, 0.24, 2.19]} rotation={[Math.PI / 2, -0.09, -Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_520_Tasten_0_Material074_37001_0.geometry} material={materials['Material.074_37.001']} position={[0.955, 0.24, 2.19]} rotation={[Math.PI / 2, -0.09, -Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_520_Tasten_0_Material074_38001_0.geometry} material={materials['Material.074_38.001']} position={[0.955, 0.24, 2.19]} rotation={[Math.PI / 2, -0.09, -Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Cube003_Material001_0_Material074_30001_0.geometry} material={materials['Material.074_30.001']} position={[-2.046, 4.343, -2.18]} rotation={[2.993, -1.081, -0.132]} scale={[3.253, 0.31, 0.041]} >
         <meshBasicMaterial map={texture}/>
      </mesh>
      <mesh geometry={nodes.Plane_Material053_0_Material074_21001_0.geometry} material={materials['Material.074_21.001']} position={[1.211, 0.188, -0.637]} rotation={[Math.PI, 0, 0]} scale={[0.959, 0.924, 1.187]} />
      <mesh geometry={nodes.Object_6_Screen001_0.geometry} material={materials['Screen.001']} position={[-2.843, 1.363, 2.727]} rotation={[-Math.PI / 2, 0.272, Math.PI / 2]} scale={11.811} />
      <mesh geometry={nodes.Object_6_Keyboard001_0.geometry} material={materials['Keyboard.001']} position={[-2.843, 1.363, 2.727]} rotation={[-Math.PI / 2, 0.272, Math.PI / 2]} scale={11.811} />
      <mesh geometry={nodes.Object_6_Light001_0.geometry} material={materials.PaletteMaterial003} position={[-2.843, 1.363, 2.727]} rotation={[-Math.PI / 2, 0.272, Math.PI / 2]} scale={11.811} />
      <mesh geometry={nodes.Cooling_stand_6chashki001_0.geometry} material={materials.PaletteMaterial004} position={[-2.422, 0.49, 2.748]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.117} />
      <mesh geometry={nodes.Object_90_Material011_0.geometry} material={materials['Material.011']} position={[-1.926, 4.471, -3.623]} rotation={[0.053, -0.345, -0.097]} scale={[1.946, 1.947, 0.812]} />
    </group>
  )
}

useGLTF.preload('models/gaming_setup-transformed.glb')
